CREATE TABLE animals (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  sci_name     TEXT,
  emoji        TEXT,
  tier         TEXT CHECK (tier IN ('L','S','A','B','C','D')),
  tier_label   TEXT,
  pts          INT,
  status       TEXT,
  status_label TEXT,
  where_find   TEXT,
  habitat      TEXT,
  wiki_url     TEXT,
  is_active    BOOLEAN DEFAULT TRUE
);

ALTER TABLE animals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Animals are publicly viewable"
  ON animals FOR SELECT
  USING (TRUE);

INSERT INTO animals (id, name, sci_name, emoji, tier, tier_label, pts, status, status_label, where_find, habitat, wiki_url) VALUES
  ('sapo-flamenguinho','Sapo-Flamenguinho','Mascote','🐸','L','Lendário',1000,'LC','Pouco preocupante','Noites chuvosas em locais específicos','Místico','https://pt.wikipedia.org/wiki/Sapo'),
  ('onca-pintada','Onça-pintada','Panthera onca','🐆','L','Lendário',800,'EN','Em Perigo','Matas densas e grotões','Floresta Atlântica','https://pt.wikipedia.org/wiki/Panthera_onca'),
  ('lobo-guara','Lobo-guará','Chrysocyon brachyurus','🐺','L','Lendário',600,'VU','Vulnerável','Campos e cerrado de altitude','Cerrado/Campo','https://pt.wikipedia.org/wiki/Lobo-guar%C3%A1'),
  ('onca-parda','Onça-parda','Puma concolor','🦁','S','Mítico',450,'LC','Pouco preocupante','Áreas extensas de mata','Floresta Atlântica','https://pt.wikipedia.org/wiki/Puma_concolor'),
  ('jaguatirica','Jaguatirica','Leopardus pardalis','🐱','S','Mítico',350,'LC','Pouco preocupante','Matas e capoeiras','Floresta Atlântica','https://pt.wikipedia.org/wiki/Jaguatirica'),
  ('ariranha','Ariranha','Pteronura brasiliensis','🦦','S','Mítico',500,'EN','Em Perigo','Rios e lagoas de águas claras','Aquático','https://pt.wikipedia.org/wiki/Ariranha'),
  ('anta','Anta','Tapirus terrestris','🫏','S','Mítico',400,'VU','Vulnerável','Próximo a rios e brejos','Floresta Atlântica','https://pt.wikipedia.org/wiki/Anta'),
  ('veado-campeiro','Veado-campeiro','Ozotoceros bezoarticus','🦌','S','Mítico',280,'NT','Quase ameaçado','Campos abertos e cerrado','Cerrado/Campo','https://pt.wikipedia.org/wiki/Veado-campeiro'),
  ('cachorro-do-mato','Cachorro-do-mato','Cerdocyon thous','🦊','A','Épico',200,'LC','Pouco preocupante','Matas e bordas de capoeira','Floresta/Campo','https://pt.wikipedia.org/wiki/Cachorro-do-mato'),
  ('quati','Quati','Nasua nasua','🦝','A','Épico',180,'LC','Pouco preocupante','Matas e capoeiras','Floresta Atlântica','https://pt.wikipedia.org/wiki/Quati'),
  ('paca','Paca','Cuniculus paca','🐭','A','Épico',220,'LC','Pouco preocupante','Próximo a rios e grotões','Floresta Ombrófila','https://pt.wikipedia.org/wiki/Paca'),
  ('bugio','Bugio','Alouatta guariba','🦍','A','Épico',200,'VU','Vulnerável','Dossel da mata','Floresta Atlântica','https://pt.wikipedia.org/wiki/Bugio'),
  ('jacu','Jacu','Penelope obscura','🦃','A','Épico',140,'LC','Pouco preocupante','Bordas de mata e capoeiras','Floresta Atlântica','https://pt.wikipedia.org/wiki/Jacu'),
  ('urutau','Urutau','Nyctibius griseus','🦉','A','Épico',150,'LC','Pouco preocupante','Galhos secos e troncos','Floresta Atlântica','https://pt.wikipedia.org/wiki/Urutau'),
  ('jararaca','Jararaca','Bothrops jararaca','🐍','A','Épico',250,'LC','Pouco preocupante','Chão da mata','Floresta Atlântica','https://pt.wikipedia.org/wiki/Jararaca'),
  ('caninana','Caninana','Spilotes pullatus','🐍','A','Épico',160,'LC','Pouco preocupante','Matas e áreas abertas','Floresta Atlântica','https://pt.wikipedia.org/wiki/Caninana'),
  ('seriema','Seriema','Cariama cristata','🦩','B','Raro',80,'LC','Pouco preocupante','Campos abertos e cerrado','Cerrado/Campo','https://pt.wikipedia.org/wiki/Seriema'),
  ('coruja','Coruja-buraqueira','Athene cunicularia','🦉','B','Raro',70,'LC','Pouco preocupante','Campos abertos e tocas no chão','Campo','https://pt.wikipedia.org/wiki/Coruja-buraqueira'),
  ('beija-flor','Beija-flor-tesoura','Eupetomena macroura','🌸','B','Raro',90,'LC','Pouco preocupante','Jardins e bordas de mata','Floresta/Urbano','https://pt.wikipedia.org/wiki/Beija-flor-tesoura'),
  ('trinca-ferro','Trinca-ferro','Saltator similis','🐦','B','Raro',60,'LC','Pouco preocupante','Matas e capoeiras','Floresta Atlântica','https://pt.wikipedia.org/wiki/Trinca-ferro'),
  ('tucano','Tucano-de-bico-verde','Ramphastos dicolorus','🦅','B','Raro',100,'LC','Pouco preocupante','Dossel e bordas de mata','Floresta Atlântica','https://pt.wikipedia.org/wiki/Tucano-de-bico-verde'),
  ('jatai','Jataí','Tetragonisca angustula','🐝','B','Raro',50,'LC','Pouco preocupante','Ocos de árvores e muros','Floresta/Urbano','https://pt.wikipedia.org/wiki/Jata%C3%AD'),
  ('teiu','Teiú','Salvator merianae','🦎','B','Raro',80,'LC','Pouco preocupante','Clareiras e bordas de mata','Floresta/Campo','https://pt.wikipedia.org/wiki/Tei%C3%BA'),
  ('gaviao','Gavião-carijó','Rupornis magnirostris','🦅','B','Raro',90,'LC','Pouco preocupante','Matas abertas e bordas','Floresta/Campo','https://pt.wikipedia.org/wiki/Gavi%C3%A3o-carij%C3%B3'),
  ('tie-sangue','Tiê-sangue','Ramphocelus bresilius','🐦','B','Raro',70,'LC','Pouco preocupante','Bordas de mata e restinga','Floresta Atlântica','https://pt.wikipedia.org/wiki/Ti%C3%AA-sangue'),
  ('sabia','Sabiá-laranjeira','Turdus rufiventris','🐦','C','Comum',30,'LC','Pouco preocupante','Jardins e matas','Floresta/Urbano','https://pt.wikipedia.org/wiki/Sabi%C3%A1-laranjeira'),
  ('capivara','Capivara','Hydrochoerus hydrochaeris','🦫','C','Comum',35,'LC','Pouco preocupante','Margens de rios e lagoas','Brejo/Rio','https://pt.wikipedia.org/wiki/Capivara'),
  ('gamba','Gambá-de-orelha-branca','Didelphis albiventris','🦨','C','Comum',25,'LC','Pouco preocupante','Áreas urbanas e matas','Floresta/Urbano','https://pt.wikipedia.org/wiki/Gamb%C3%A1-de-orelha-branca'),
  ('joao-de-barro','João-de-barro','Furnarius rufus','🐦','C','Comum',28,'LC','Pouco preocupante','Campos abertos e postes','Campo/Urbano','https://pt.wikipedia.org/wiki/Jo%C3%A3o-de-barro'),
  ('rolinha','Rolinha','Columbina talpacoti','🕊️','C','Comum',20,'LC','Pouco preocupante','Áreas abertas e urbanas','Urbano/Campo','https://pt.wikipedia.org/wiki/Rolinha'),
  ('sapo-cururu','Sapo-cururu','Rhinella schneideri','🐸','C','Comum',20,'LC','Pouco preocupante','Próximo a corpos d''água','Brejo/Rio','https://pt.wikipedia.org/wiki/Sapo-cururu'),
  ('camundongo','Camundongo-do-mato','Oligoryzomys nigripes','🐀','C','Comum',15,'LC','Pouco preocupante','Chão da mata e roças','Floresta/Campo','https://pt.wikipedia.org/wiki/Rato-do-mato'),
  ('abelha','Abelha-europeia','Apis mellifera','🐝','C','Comum',18,'LC','Pouco preocupante','Jardins e campos floridos','Campo/Urbano','https://pt.wikipedia.org/wiki/Abelha-europeia'),
  ('ra','Rã-manteiga','Leptodactylus ocellatus','🐸','C','Comum',22,'LC','Pouco preocupante','Brejos e poças','Brejo/Rio','https://pt.wikipedia.org/wiki/R%C3%A3-manteiga'),
  ('bem-te-vi','Bem-te-vi','Pitangus sulphuratus','🐦','D','Muito Comum',12,'LC','Pouco preocupante','Áreas abertas e urbanas','Urbano/Campo','https://pt.wikipedia.org/wiki/Bem-te-vi'),
  ('pardal','Pardal','Passer domesticus','🐦','D','Muito Comum',8,'LC','Pouco preocupante','Áreas urbanas e rurais','Urbano','https://pt.wikipedia.org/wiki/Pardal'),
  ('pombo','Pombo-doméstico','Columba livia','🕊️','D','Muito Comum',6,'LC','Pouco preocupante','Áreas urbanas e praças','Urbano','https://pt.wikipedia.org/wiki/Pombo-dom%C3%A9stico'),
  ('lagartixa','Lagartixa-doméstica','Hemidactylus mabouia','🦎','D','Muito Comum',10,'LC','Pouco preocupante','Paredes e muros','Urbano','https://pt.wikipedia.org/wiki/Lagartixa-dom%C3%A9stica'),
  ('formiga-sauva','Formiga-saúva','Atta sexdens','🐜','D','Muito Comum',8,'LC','Pouco preocupante','Formigueiros no chão','Solo','https://pt.wikipedia.org/wiki/Formiga-cortadeira'),
  ('mosquito','Mosquito-pernilongo','Culex quinquefasciatus','🦟','D','Muito Comum',5,'LC','Pouco preocupante','Áreas úmidas e urbanas','Urbano/Brejo','https://pt.wikipedia.org/wiki/Culex_quinquefasciatus'),
  ('mariposa','Mariposa','Ascalapha odorata','🦋','D','Muito Comum',6,'LC','Pouco preocupante','Áreas abertas e urbanas','Floresta/Urbano','https://pt.wikipedia.org/wiki/Bruxa_(mariposa)'),
  ('borboleta','Borboleta-monarca','Danaus plexippus','🦋','D','Muito Comum',10,'LC','Pouco preocupante','Jardins e campos','Campo/Urbano','https://pt.wikipedia.org/wiki/Borboleta-monarca'),
  ('taturana','Taturana','Lonomia obliqua','🐛','D','Muito Comum',15,'LC','Pouco preocupante','Troncos de árvores','Floresta Atlântica','https://pt.wikipedia.org/wiki/Taturana');
